import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '@/components/client/Header';
import SearchResults from '@/components/client/SearchResults';
import WaiterButton from '@/components/client/WaiterButton';
import MenuDataProvider from '@/providers/MenuDataProvider';
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">


        <MenuDataProvider>
          <Header />
          <SearchResults />

          {children}
          <Suspense>

            <WaiterButton />
          </Suspense>
        </MenuDataProvider>

      </body>
    </html>
  );
}
